spring:
  application:
    name: user_service
    description: User Service microservice responsible for authentication, authorization, role management, and user creation.
    version: 1.0.0
  profiles:
    active: local

app:
  api:
    prefix: /api/v1