INSERT INTO roles (name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO roles (name) VALUES (2, 'ROLE_OWNER');
INSERT INTO roles (name) VALUES (3, 'ROLE_WORKER');
INSERT INTO roles (name) VALUES (4, 'ROLE_CUSTOMER');
